# Generated by Django 3.2 on 2021-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prvi_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vjezbe', models.CharField(max_length=200)),
                ('serije', models.IntegerField(max_length=30)),
                ('ponavljanja', models.IntegerField(max_length=30)),
            ],
        ),
    ]
