# Generated by Django 3.2 on 2021-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prvi_program',
            options={'verbose_name_plural': 'Prvi_program'},
        ),
        migrations.AlterField(
            model_name='prvi_program',
            name='ponavljanja',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prvi_program',
            name='serije',
            field=models.IntegerField(),
        ),
    ]
