# Generated by Django 3.2 on 2021-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210630_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='prvi_program',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
