# Generated by Django 3.2 on 2021-06-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_prvi_program_gif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('cijena', models.IntegerField()),
                ('serije', models.IntegerField()),
                ('kategorije', models.CharField(max_length=200)),
            ],
        ),
    ]
