# Generated by Django 3.2 on 2021-06-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_placanje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placanje',
            options={'verbose_name_plural': 'Placanje'},
        ),
        migrations.RemoveField(
            model_name='placanje',
            name='serije',
        ),
    ]
