# Generated by Django 3.2 on 2021-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210630_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placanje',
            name='kategorije',
            field=models.TextField(),
        ),
    ]
