# Generated by Django 3.2 on 2021-07-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_placanje_sest_mjeseci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placanje_sest_mjeseci',
        ),
    ]
