# Generated by Django 3.2 on 2021-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_placanje_sest_mjeseci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prvi_program',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
