# Generated by Django 3.2 on 2021-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_prvi_program_utorak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prvi_program',
            name='ponavljanja',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='prvi_program_utorak',
            name='ponavljanja',
            field=models.CharField(max_length=300),
        ),
    ]
