# Generated by Django 3.2 on 2021-07-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_prvi_program_cetvrtak_prvi_program_petak_prvi_program_srijeda_prvi_program_subota'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prvi_program',
            new_name='Prvi_program_ponedjeljak',
        ),
        migrations.AlterModelOptions(
            name='prvi_program_ponedjeljak',
            options={'verbose_name_plural': 'Prvi_program_ponedjeljak'},
        ),
    ]
