# Generated by Django 3.2 on 2021-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_program_yoga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_yoga',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/yoga'),
        ),
    ]
