# Generated by Django 3.2 on 2021-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_misicna_definicija3_petak_misicna_definicija3_ponedjeljak_misicna_definicija_srijeda3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misicna_definicija3_nedjelja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='images/%y/definicija3/nedjelja')),
                ('vjezbe', models.CharField(max_length=200)),
                ('serije', models.IntegerField()),
                ('ponavljanja', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Misicna_definicija3_nedjelja',
            },
        ),
    ]
