# Generated by Django 3.2 on 2021-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='prvi_program_ponedjeljak',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
